spring:
    datasource:
        url: jdbc:sqlserver://machine_name(can give vdi machine id)\MSSQLSERVER2012;DatabaseName=database_name;sendStringParametersAsUnicode=true;integratedSecurity=true
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        max-active: 20
    jpa:
        hibernate:
             naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        database: SQL_SERVER
        show-sql: true
        properties:
             hibernate:
                 dialect: org.hibernate.dialect.SQLServer2012Dialect
                 id:
                  new_generator_mappings: false
    application:
     name: project_name
     jmx:  
        enabled: false 